# Generated by Django 5.2.3 on 2025-06-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('href', models.TextField()),
                ('logo_alt', models.TextField()),
                ('logo', models.TextField()),
                ('display_name', models.TextField()),
                ('header_placeholder', models.TextField()),
                ('hero_placeholder', models.TextField()),
                ('hero_button', models.TextField()),
                ('prev', models.TextField()),
                ('next', models.TextField()),
                ('see_more', models.TextField()),
                ('legal_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('content_title', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=10)),
                ('tag_title', models.CharField(max_length=255)),
                ('website_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FooterSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.footer')),
            ],
        ),
        migrations.AddField(
            model_name='footer',
            name='hero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='core.hero'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.hero')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('href', models.CharField(blank=True, max_length=255, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.tag')),
            ],
        ),
    ]
