# Generated by Django 5.2.1 on 2025-06-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('href', models.TextField()),
                ('logo_alt', models.TextField()),
                ('logo', models.TextField()),
                ('display_name', models.TextField()),
                ('header_placeholder', models.TextField()),
                ('hero_placeholder', models.TextField()),
                ('hero_button', models.TextField()),
                ('prev', models.TextField()),
                ('next', models.TextField()),
                ('see_more', models.TextField()),
                ('legal_info', models.TextField()),
            ],
        ),
    ]
