# Generated by Django 5.2.3 on 2025-06-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='url',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='href',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
