# Generated by Django 5.2.3 on 2025-06-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_subcategory_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='url_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
