# Generated by Django 5.2.3 on 2025-06-12 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_modelpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nikname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_url', models.CharField(max_length=255)),
                ('about_model', models.TextField()),
                ('footer_button_url', models.CharField(max_length=255)),
                ('sign_up_here_url', models.CharField(max_length=255)),
                ('hero_url', models.CharField(max_length=255)),
                ('last_updated', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPopularTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='popular_times', to='core.model')),
            ],
        ),
        migrations.CreateModel(
            name='ModelStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='core.model')),
            ],
        ),
        migrations.CreateModel(
            name='ModelTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('tag_name', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.model')),
            ],
        ),
    ]
