# Generated by Django 5.2.3 on 2025-06-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_model_modelpopulartime_modelstatistic_modeltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='avatar',
            field=models.CharField(default='', max_length=255),
        ),
    ]
