# Generated by Django 5.2.3 on 2025-06-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_model_name_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='avatar',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ModelPopularTime',
        ),
    ]
