# Generated by Django 5.2.3 on 2025-06-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_model_avatar_delete_modelpopulartime'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='popular_times',
            field=models.JSONField(default=dict),
        ),
    ]
